### ISSUE TITLE
BWANG INI KENAPA GINI BWANG.. APP NYA BUAT APA BWANG

### ISSUE THREAD

**Issue by Zilfs** [Bagusaliefya/lelang-ukk#1]
![IMG_7986](https://github.com/Bagusaliefya/lelang-ukk/assets/117014577/28b539c3-7b56-4c43-bf41-ccfd9364ffa7)

**Comment by Bagusaliefya** [comment]
maaf bwang lagi di renovasi, diem ya dek

**Comment by Zilfs** [comment]
Maaf bang 
![WhatsApp Image 2024-01-21 at 22 01 18_d153e463](https://github.com/Bagusaliefya/lelang-ukk/assets/117014577/57f78c76-49cb-437d-9c10-3397c2234c46)
