### ISSUE TITLE
#Quotes 1

### ISSUE THREAD

**Issue by FarhanGinting** [Bagusaliefya/lelang-ukk#2]
![WhatsApp Image 2024-02-05 at 00 04 23](https://github.com/Bagusaliefya/lelang-ukk/assets/118242884/c29e15ce-bb87-4183-b8e0-fadf291e9550)

**Comment by Zilfs** [comment]
https://github.com/Bagusaliefya/lelang-ukk/assets/117014577/59df83ea-beff-4c41-a594-42bec3222969

**Comment by ShawBoyy** [comment]
![dummy](https://github.com/Bagusaliefya/lelang-ukk/assets/118329148/5f245212-8086-4809-a1e5-5228929cf785)
minum arak🍻

**Comment by ShawBoyy** [comment]
![Uploading a2631f1f-ef6c-47ed-b02f-efb41bec1056.jpg…]()
